### ISSUE TITLE
.cyclic.js is missing

### ISSUE THREAD

**Issue by gislenius** [28msec/layoutmodel-renderer-angular#23]

**Comment by wcandillon** [comment]
@gislenius What is .cyclic.js?

**Comment by gislenius** [comment]
Hi,

It's a file that is needed to do npm install, and that's not here.

Kind regards,
Ghislain


On Thu, Mar 26, 2015 at 4:16 PM, William Candillon <notifications@github.com

**Comment by wcandillon** [comment]
Can you point me to an error log or to something in the source code?

**Comment by gislenius** [comment]
Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "./cyclic.js"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.10

npm ERR! missing script: ./cyclic.js
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/28msec/Code/github/layoutmodel-renderer-angular/node_modules/grunt-ng-constant/node_modules/js2coffee/npm-debug.log
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.10
npm ERR! code ELIFECYCLE

npm ERR! js2coffee@0.2.7 preinstall: `npm run-script ./cyclic.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js2coffee@0.2.7 preinstall script 'npm run-script ./cyclic.js'.
npm ERR! This is most likely a problem with the js2coffee package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run-script ./cyclic.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls js2coffee
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/28msec/Code/github/layoutmodel-renderer-angular/npm-debug.log

**Comment by gislenius** [comment]
\
> js2coffee@0.2.7 preinstall /Users/28msec/Code/github/layoutmodel-renderer-angular/node_modules/grunt-ng-constant/node_modules/js2coffee
> npm run-script ./cyclic.js

**Comment by wcandillon** [comment]
The following should work:
```bash
$rm -rf node_modules
$npm install npm -g
```

Please feel free to reopen if the issue persists.

**Comment by wcandillon** [comment]
@gislenius I've been investigating the issue. You've probably been using 0.10.33. Switching to 0.10.66 should solve the problem. This is related to a grunt package that we should remove anyways. I'll ask you more details offline.
