### ISSUE TITLE
When there are multiple header axes, members are shown dark blue but should appear light blue.

### ISSUE THREAD

**Issue by ghislainfourny** [28msec/layoutmodel-renderer-angular#25]

**Comment by gislenius** [comment]
http://rendering.secxbrl.info/#?url=http:%2F%2Fsecxbrl-923.28.io:80%2Fv1%2F_queries%2Fpublic%2Fapi%2Fspreadsheet-for-component.jq%3Ftoken%3Dfoobar%26aid%3D0000858877-15-000013%26format%3Djson%26role%3Dhttp%253A%252F%252Fwww.cisco.com%252Frole%252FShareholdersEquityAdditionalInformationDetails%26hypercube%3Dus-gaap%253AScheduleOfStockByClassTable%26profile-name%3Dsec%26eliminate%3Dtrue%26validate%3Dtrue

**Comment by gislenius** [comment]
"CellConstraints": {} -> dark blue
"CellConstraints": {(: non-empty: } -> light blue
